#include "DBoW3/DBoW3.h"
#include <opencv2/core/core.hpp>
#include <opencv2/highgui/highgui.hpp>
#include <opencv2/features2d/features2d.hpp>
#include <iostream>
#include <vector>
#include <string>
#include <iomanip> // For std::setw and std::setfill

using namespace cv;
using namespace std;

/***************************************************
 * 本节演示了如何根据前面训练的字典计算相似性评分
 * ************************************************/
int main(int argc, char **argv) {
    // read the images and database  
    cout << "reading database" << endl;
    // DBoW3::Vocabulary vocab("./kitti_00_all.yml.gz");
        DBoW3::Vocabulary vocab("./orbvoc.dbow3");



    // DBoW3::Vocabulary vocab("./vocab_larger.yml.gz");  // use large vocab if you want: 
    if (vocab.empty()) {
        cerr << "Vocabulary does not exist." << endl;
        return 1;
    }
    cout << "reading images... " << endl;
    vector<Mat> images;

    for (int i = 0; i <= 4540; i++) // Looping up to 4540
    {
        stringstream pathStream;
        pathStream << "./dataset/KITTI/data_odometry_gray/dataset/sequences/00/image_0/" 
                   << setw(6) << setfill('0') << i << ".png";
        string path = pathStream.str();
        Mat image = imread(path);
        if (!image.empty()) {
            images.push_back(image);
        } else {
            cerr << "Failed to load image at: " << path << endl;
        }
    }


    // NOTE: in this case we are comparing images with a vocabulary generated by themselves, this may lead to overfit.
    // detect ORB features
    cout << "detecting ORB features ... " << endl;
    Ptr<Feature2D> detector = ORB::create();
    vector<Mat> descriptors;
    for (Mat &image:images) {
        vector<KeyPoint> keypoints;
        Mat descriptor;
        detector->detectAndCompute(image, Mat(), keypoints, descriptor);
        descriptors.push_back(descriptor);
    }

    // we can compare the images directly or we can compare one image to a database 
    // images :
    // cout << "comparing images with images " << endl;
    // for (int i = 1; i <= images.size(); i++) {
    //     DBoW3::BowVector v1;
    //     vocab.transform(descriptors[i], v1);
    //     for (int j = i; j < images.size(); j++) {
    //         DBoW3::BowVector v2;
    //         vocab.transform(descriptors[j], v2);
    //         double score = vocab.score(v1, v2);
    //         cout << "image " << i << " vs image " << j << " : " << score << endl;
    //     }
    //     cout << endl;
    // }

    // or with database 
    cout << "comparing images with database " << endl;
    DBoW3::Database db(vocab, false, 0);
    for (int i = 0; i < descriptors.size(); i++)
        db.add(descriptors[i]);
    cout << "database info: " << db << endl;

    std::ofstream fout("dbow_result.txt");  // Open output file

    if (!fout) {
        std::cerr << "Error: Unable to open file for writing.\n";
        return 0;
    }


    for (int i = 0; i < descriptors.size(); i++) {
        DBoW3::QueryResults ret;
        db.query(descriptors[i], ret, 20);      // max result=4
        // cout << "Top 20 most similar images to " << i << " returns " << ret << endl << endl;
        // print(f"\nTop 20 most similar images to {os.path.basename(image_path)}:", file = f)
        std::ostringstream oss;
        oss << "\nTop 20 most similar images to " << setw(6) << setfill('0') << i << ".png" << ": " << ret << "\n";
        // oss<<ret<< "\n";
        fout << oss.str();
    }
    fout.close();
}